### ISSUE TITLE
Date field from database didn't parse correctly after uodate to version f7fa646

### ISSUE THREAD

**Issue by duckbert** [Mohlsson/ReplayLightsHistory#18]
Sorry to bother you again but unfortunately after updating to version f7fa646 I get the following error message for all my lights: 2020-07-31 07:05:37.411600 INFO replay_lights: First seen light.elternzimmer, adding to state table with state off
2020-07-31 07:05:37.413724 INFO replay_lights: Date field from database didn't parse correctly so skipping record

The previous version of ReplayLightsHIstory was working well for em after installing the  PyMySQL package
I am using MariaDB and this is my config. 
replay_lights:
  databaseType: MariaDB
  databaseUser: "****"
  databasePassword: "*****"
  module: replay_lights
  class: ReplayLights
  numberOfDaysBack: 7
  deviceType: "light"
  enableTag: "input_boolean.light_replay_enabled"
  enableVal: "on"
  smartControlledByDumb: "light.bad_spot_1_2,light.bad_spot_2_2,light.bad_spot_3_2,light.buro_spot_1_2,light.buro_spot_2_2,light.buro_spot_3_2,light.buro_spot_4_2,light.elternlicht_2,light.esstischlampe_2,light.flur_spot_1_2,light.flur_spot_2_2,light.flur_spot_3_2,light.flur_spot_4_2,light.flur_spot_5_2,light.hue_ambiance_panel_1_2,light.hue_lightstrip_outdoor_1_2,light.hue_outdoor_spot_1_2,light.hue_outdoor_spot_2_2,light.insel_spot_1_2,light.insel_spot_2_2,light.kinderzimmerlampe_2,light.kinderzimmerlicht,light.kuchen_spot_1_2,light.kuchen_spot_2_2,light.kuchen_spot_3_2,light.kuchen_spot_4_2,light.kuchen_spot_5_2,light.stehlampe_2,light.treppenlicht_2,light.vorplatzlicht_1_2,light.vorplatzlicht_2_2,light.vorplatzlicht_3_2,light.wohnzimmerlampe_2"
  excludeList: "light.aussen,light.badezimmer,light.buero,light.carport,light.dachgeschoss,light.deck,light.elternschlafzimmer,light.entree,light.entree_spot_1_2,light.entree_spot_2_2,light.erdgeschoss,light.esszimmer,light.haus,light.kellerflur,light.kellertreppe,light.kinderschlafzimmer,light.kuche"

**Comment by Mohlsson** [comment]
No worries, I think there is a discepancy between MySQL and MaraiDB in the date/time formatting. @JoHa-git do you have time to have a look at this as I do not use MariaDB.

**Comment by JoHa-git** [comment]
I created a pull request on that should fix the issue.

**Comment by duckbert** [comment]
Hi, this seems to have fixed my issue. Thank you so much.
