### ISSUE TITLE
Question not an issue.

### ISSUE THREAD

**Issue by rananna** [Mohlsson/ReplayLightsHistory#26]
Could you please explain to me what would happen if I triggered the routine by armed away, set it for 7 days back and left fir two weeks?
Would the routine repeat every day I am gone for the same day (7 days ago)? Would it only do one day and stop? Can I set a randomized day pattern? Basically how does the routine handle an extended absence?

**Comment by Mohlsson** [comment]
The first week replays the previous week, but also all changes are registered for that week so that the second week replays the replayed first week. This plugin do not support random events, there are other plugins that do this.

**Comment by rananna** [comment]
Thanks!
